### ISSUE TITLE
--compilers option

### ISSUE THREAD

**Issue by shinout** [kt3k/kocha#19]
In mocha, `--compilers` option sets preprocessing scripts, usually needed for altJS.

**Comment by kt3k** [comment]
Please use `--require` option for the moment.

For coffee-script

    kocha --require coffee-script/register <files>

For babel

    kocha --require babel-register <files>

See [examples](https://github.com/kt3k/kocha/commit/6d9469f0fded8c3df0a0585e4d8b30071fef3a8d) just in case.

I'm still wondering if we should implement `--compilers` option in addition to `--require` option.

**Comment by kt3k** [comment]
The difference between `--compilers js:babel-register` and `--require babel-register` is about watching behavior. The former add .js extension to watch paths and the latter doesn't.

We are not going to implement watch feature because that's separate task from test runner and we want to keep the kocha as simple as possible. Instead I recommend to use tools like `chokidar-cli` for watching files on unit testing.

Please reopen this if you find reasonable use cases of `--compilers` over `--require`.
