### ISSUE TITLE
[request] compatibility document

### ISSUE THREAD

**Issue by teppeis** [kt3k/kocha#2]
Thank you for awesome work!
I think clearer document of current compatibility between kocha and mocha is very useful for both users and contributors.
cf. https://twitter.com/azu_re/status/871561253667221507

**Comment by kt3k** [comment]
@teppeis cc @azu
Thanks for the feedback! :)

Kocha is mostly compatible with BDD mode of mocha with its spec reporeter in CommonJS environment. It must be 'very' compatible at the execution of tests. Most mocha tests should be migrated to kocha by just adding `require('kocha')` statements at the top. ( Does this answer your question? )

However I started creating this library just 5 days ago, and I can't guarantee it works perfectly in any edge cases. There could be something I'm not aware. Please file an issue if you find any incompatiblitiy!

**Comment by kt3k** [comment]
For example [this](https://github.com/kt3k/layout1/commit/970b3832cc28399845ad019b88665956127003dc) is what I needed to do when I migrated one of my small npm lib from mocha to kocha.

**Comment by azu** [comment]
@kt3k Thanks for answer!
It is helpful for me.

If you could describe following things in README, it is helpful for new user.

- Goal
  - e.g.) https://github.com/brn/fuel#future
  - I think that kocha will not complete drop-in replacement for mocha
  - Because, kocha aim to expose method like `it` that is defined as global in `mocha`
  - The user can understand the goal ot the project
- Difference (with mocha)
  - e.g.) https://preactjs.com/guide/differences-to-react
  - It is similar with Goal
  - The user can understand the difference between mocha and kocha
- Migration path
  - e.g. ) https://github.com/micromatch/micromatch#switching-to-micromatch
  - The user can understand migration way from mochat to kocha
  - It will be a more concrete example.
  - [Your comment](https://github.com/kt3k/kocha/issues/2#issuecomment-306107449) is very helpful

**Comment by kt3k** [comment]
@azu 
Thanks for guiding how to document the project purpose well! That's very helpful to me.

I documented the project goals at #6. Thanks.

**Comment by azu** [comment]
@kt3k Thanks! 
Nice documents :sparkles:

**Comment by teppeis** [comment]
@kt3k nice work!
